[package]
name = "check_external_command_version_for_compatibility"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = "1.0.16"
error-chain = "0.12.4"
