[package]
name = "check_if_api_resource_exists"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
