[package]
name = "compile_and_link_statically_to_bundled_cpp_library"
version = "0.1.0"
edition = "2021"

build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"

[build-dependencies]
cc = "1"