[package]
name = "calculate_sha256_sum_of_iso_files_concurrently"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"
num_cpus = "1.13.1"
walkdir = "2.3.2"
ring = "0.16.20"
