[package]
name = "deserialize_serialize_matrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.32.2", features = ["serde-serialize"] }
serde_json = "1.0.96"
