[package]
name = "verifying_tan_is_equal_to_sin_divided_by_cos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
