[package]
name = "conventions"
version = "0.1.0"
edition = "2021"

default-run = "conventions"

[[bin]]
name = "conventions"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
