[package]
name = "decompress_tarball_while_removing_prefix_from_paths"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
flate2 = "1.0.24"
tar = "0.4.38"
